version: 2

build:
  image: "latest"
  os: ubuntu-22.04
  tools:
    python: "3.10"

#python:
#  version: "3.10"
#  install:
#    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
